### PR TITLE
making sed work with both unix and mac os x

### LINKED ISSUE #3: Does not work on Mac
There's a problem running the create_module.sh script on Mac.

This seem to be due to version missmatch of SED. When running the same command in an Ubuntu Docker container it works fine.

```
$ bash -c "$(curl -sL https://raw.githubusercontent.com/roramirez/MagicMirror-Module-Template/master/create_module.sh)"
MagicMirror installation not found.
Please input its path now (or restart script in its directory): /path
Insert your module name: MyModule
Do you want create in /path/module/MyModule (y/N) y
Pickup a license
  1. MIT (Default)
  2. ISC
Choice: 1
Type a short description of what your module does (leave empty to insert a Todo)
: Todo
Cloning into '/var/folders/s9/tkvlqcy57w37x46r69d2x9b40000gn/T/tmp.jUQrYWPk'...
remote: Counting objects: 160, done.
remote: Total 160 (delta 0), reused 0 (delta 0), pack-reused 160
Receiving objects: 100% (160/160), 22.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (82/82), done.
Checking connectivity... done.
sed: 1: "/path/module/MyModule ...": invalid command code m
sed: 1: "/path/module/MyModule ...": invalid command code m
sed: 1: "/path/module/MyModule ...": invalid command code m
sed: 1: "/path/module/MyModule ...": invalid command code m
sed: 1: "/path/module/MyModule ...": invalid command code m
Initialized empty Git repository in /path/module/MyModule/.git/
```

Running this manually shows me there's an error in CHANGELOG.md but that makes no sense at all.

```
sed -i s/\{\{MODULE_NAME\}\}/MyModule/g module/MyModule/*.*
sed: 1: "CHANGELOG.md": invalid command code C
```

### PR DESCRIPTION
**Pull request by morozgrafix**
Workaround for `sed` differences between GNU and OS X versions.

Hey Rodrigo, I know this repo is somewhat old. I grabbed it to make another MMM module and found that issue from a while ago. Here is my proposed solution based on https://stackoverflow.com/a/51060063

fixes #3

### CODE REVIEW

**Comment by morozgrafix** [comment]
Travis build is failing due to some `eslint` errors but I don't think it has anything to do with my changes. 🤷‍♂ 
```
$ grunt
Loading "eslint.js" tasks...ERROR
>> SyntaxError: Unexpected token ...
Warning: Task "eslint" not found. Use --force to continue.
Aborted due to warnings.
```

**Comment by morozgrafix** [comment]
Bumped some of the package versions and bumped node versions for travis runs. Tests are passing now.

**Comment by roramirez** [comment]
Hey Sergey, Thanks you! This is a good work for issue with sed. 

PS: Never a repo is too old if work for someones ;)

**Comment by roramirez** [comment]
I've change the PR against the `develop` branch

**Pull request merged**
